### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kkkn2024** [bkunzhang/t#3]
Since version 2.2.x, the spring boot documentation has no `htmlsingle` variant anymore.

This will cause all links across the web pointing to `https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/` to break, once 2.2.0 goes GA.

I propose to put a placeholder `index.html` under `reference/htmlsingle/` which either redirects to the new documentation or shows at least a nice information about the fact that the documentation has changed (instead of a basic 404 error page)

**Comment by bkunzhang** [comment]
![1](https://user-images.githubusercontent.com/19164121/54945413-ada95d00-4f70-11e9-9e13-7b694a8d1a04.jpg)

**Comment by kkkn2024** [comment]
![1](https://user-images.githubusercontent.com/19164121/54945463-d3366680-4f70-11e9-9364-bda25af791fb.jpg)
- tt

**Comment by bkunzhang** [comment]
> > 没发现是第一啊。
> > > 是这个页面吗?https://github.com/trending
> > 
> > 
> > 难道姿势不对吗
> 
> 确实，怎么好像被和谐了？还是要明天才能看到？

aaaa

**Comment by bkunzhang** [comment]
> > 没发现是第一啊。
> > > 是这个页面吗?https://github.com/trending
> > 
> > 
> > 难道姿势不对吗
> 
> 确实，怎么好像被和谐了？还是要明天才能看到？



> 没发现是第一啊。
> 
> > 是这个页面吗?https://github.com/trending
> 
> 难道姿势不对吗

aaaa

**Comment by kkkn2024** [comment]
> 没发现是第一啊。
> 
> > 是这个页面吗?https://github.com/trending
> 
> 难道姿势不对吗

aaaa

**Comment by kkkn2024** [comment]
> 没想到这个项目居然有这么多 star ，给各位动手能力强的同学一个建议，搞个网站，让用户可以自由、匿名提交公司的 996 情况，其他人可以进行投票确认。
> 
> 比如首页：
> 
> ![首页](https://camo.githubusercontent.com/da2fb2d5bcb66309d15aaccebcfbf3a10aad1e46/68747470733a2f2f6b6e622e696d2f696d616765732f3939365f312e706e67)
> 
> 比如公司页面：
> 
> ![公司](https://camo.githubusercontent.com/14dc62d7a1cff93ca69973b0dfcbb9b253ccd537/68747470733a2f2f6b6e622e696d2f696d616765732f3939365f322e706e67)
> 
> 比如提交页面：
> 
> ![提交](https://camo.githubusercontent.com/a3f49f4498ebf47e72de35da2ffd74641308ef1d/68747470733a2f2f6b6e622e696d2f696d616765732f3939365f332e706e67)
> 
> 作为一个表达声音的项目，不需要过多考虑提交和投票者是否真的在对应的公司，更多的是让更多人能参与表达，发出对这种犹如「高三每个中学都补课，我们不补课就落后了」的扭曲价值观的不认同。



ttt
`https://github.com/996icu/996.ICU/issues/642`

**Comment by bkunzhang** [comment]
https://github.com/bkunzhang/t/issues/4#issuecomment-477058385

**Comment by bkunzhang** [comment]
`https://github.com/bkunzhang/t/issues/4#issuecomment-477058385`

**Comment by kkkn2024** [comment]
`https://github.com/bkunzhang/t/issues/5#issuecomment-477067621`

**Comment by kkkn2024** [comment]
> https://github.com/bkunzhang/t/issues/5
